<?php
/* Homepage Konfiguration */

 $_DLRG_DOC = array (
        "glied"=>"Ortsgruppe Musterhausen e.V.",
        "gliedbz"=>"Bezirk Templatingen",
        "gliedbz_link"=>"www.bezirk.dlrg.de",
        "gliedlv"=>"Landesverband Muster",
        "gliedlv_link"=>"www.landesverband.dlrg.de",
        "picbar"=>"default.gif",
        "pictext"=>"Unser Angebot",
        "id"=>"",
        "style"=>"",
        "titel"=>"",
        "keyword"=>"Jugend, Baywatch ;-), Ausbildung, Schwimmabzeichen, Tauchen, Bootfahren, Wachdiest, Rettungswachdienst, Sainitäter, Sanitätsausbildung, Schwimmtraining, Rettungsschwimmen, Rettungssport, Ausbildung",
        "description"=>"DLRG - DLRG Musterhausen e.V., Deutsche Lebens-Rettungs-Gesellschaft Ortsgruppe Musterhausen e.V.",
        "author"=>"Webmaster",
        "email"=>"webmaster@musterhausen.dlrg.de",
        "datum"=> date("d.m.Y | H:00", filemtime($_DLRG_PATH['content'].$_DLRG_SYS['get'].".inc")),
        "bank"=> "Volksbank in Schaumburg",
        "blz"=> "255 914 13",
        "kontonr"=>"730 900 000 0",
        "spendenID"=> "",
        "wappen"=> ""
        );
 $_DLRG_MENU = array (
        "main"=>"menu",
        "quick"=>"",
        "ads"=>"",
        "sub"=>"",
        "top"=>"",
        "item"=>""
        );
 $_DLRG_CRUMB = array();

 $_DLRG_STYLE = array();
?>