<?php
/* Homepage Location */

  define("glob_lyt", '/global/layout/access/');
  define("glob_doc", '/global/document/');
  define("glob_img", '/global/image/');
  define("glob_sys", 'global/layout/access/system/');

 $_DLRG_SYS = array (
         "domain"=>"dlrg.de",
         "call"=>"index.php?doc=" );
 $_DLRG_PATH = array (
         "content"=>"content/",
         "style"=>"style/",
         "image"=>"bild/",
         "grafik"=>"grafik/" );
 $_DLRG_INC = array (
         "start"=>"index",
         "search"=>"suche",
         "sitemap"=>"sitemap",
         "impress"=>"impress",
         "tell"=>"",
         "contact"=>"kontakt",
         "access"=>"access",
         "error"=>"notfound",
         "sponsor"=>"" ,
         "banner"=>"" ,
         "bank"=>"bank",
         );
?>