      <a class="menuitem top" id="i02" href="index.php?doc=wtl_edit&amp;data=edit">Eine Ebene h&ouml;her</a>
      <a class="menuitem" id="i03" href="index.php?doc=wtl_view">Wartelisten verwalten</a>
      <div class="menusub" id="s03">
              <a class="menuitem" id="i0301" href="index.php?doc=wtl_view">Ansehen</a>
              <a class="menuitem" id="i0302" href="index.php?doc=wtl_ent">Aufnehmen</a>
              <a class="menuitem" id="i0303" href="index.php?doc=wtl_stat">Aufnahmestatistik</a>
              <a class="menuitem" id="i0312" href="index.php?doc=wtl_upload">Import/Export</a>
              <a class="menuitem" id="i0306" href="index.php?doc=wtl_inp">Eingabefelder</a>
              <a class="menuitem" id="i0307" href="index.php?doc=wtl_sel">Auswahlfelder</a>
              <a class="menuitem" id="i0308" href="index.php?doc=wtl_set">Einstellungen</a>
              <a class="menuitem" id="i0309" href="index.php?doc=wtl_user">Admins verwalten</a>
              <a class="menuitem" id="i0310" href="index.php?doc=wtl_install">Installieren</a>
              <a class="menuitem" id="i0311" href="index.php?doc=wtl_change_pw_int">Passwort ändern</a>
      </div>