                <select id="quicklink" name="quicklink" title="Schnellnavigation" size="1" onchange="window.location.href='<?php echo $_DLRG_SYS['call'] ?>'+this.value;">
                        <option selected="selected">Quicklink</option>
                        <option value="wtl_reg&amp;data=input">&nbsp;Anmelden</option>
                        <option value="wtl_edit&amp;data=edit">&nbsp;Wartestatus</option>
                </select>